### PR TITLE
Create and remove books

### PR DESCRIPTION
**Pull request by codepantha**
Changes introduced via this pull request: 👇 
- Create book actions and reducer
- Add the create and remove books functionality

### CODE REVIEW

**Review by omar-labana — CHANGES_REQUESTED** [review]
Hi @codepantherr, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [x] Please make sure to make the `Books` page the default route `/` currently I have to manually navigate to `/books` to visit  the booklist page.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [x] _[OPTIONAL]_ What is meant by the [ducks' pattern](https://github.com/erikras/ducks-modular-redux) isn't to include your reducers in a directory called `ducks` but rather to adopt a certain paradigm to map your reducers and action. Kindly move your `books` and `categories` directories directly to the `redux` folder.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by codepantha** [comment]
@omar-labana thank you 🙏 for your feedback. I have implemented your suggestions.

**Review by BrianSammit — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 

Hello @codepantherr, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by codepantha** [comment]
Thank you 🙏 @BrianSammit

**Pull request merged**
