### PR TITLE
Initialize Project With Components

### PR DESCRIPTION
**Pull request by codepantha**
Changes introduced via this pull request: 👇 ]
- Create the Books and Categories components
- Display Books as cards
- Set up /books and /categories Routes using react-router-dom
- Configure redux files using the ducks pattern
- Apply very minimal styling

### CODE REVIEW

**Comment by omar-labana** [comment]
Hi @codepantherr, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where the README file isn't updated to show a professional representation of the project, please update it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by codepantha** [comment]
@omar-labana OMG! That was an oversight 🤦‍♂️
I have fixed my mistake.

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @codepantherr, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

**Comment by codepantha** [comment]
Thank you @Ghiftee

**Pull request merged**
